name: tests

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    environment: Dev  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

#      - name: Publish
#        run: pnpm -r publish  --filter "@ertravi/txio-view-react" --no-git-checks --access=public
#        env:
#          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

